-- Load every landed file that has not been loaded yet into its bronze table.
-- Idempotent: COPY keeps per-table load history and skips files it has already loaded,
-- so re-running this after a repeated delivery adds no rows. Never run with FORCE = TRUE.
-- Columns are matched by header name; the lineage columns come from file metadata.

USE ROLE CANDIDATE_SHIVUM_ROLE;
USE WAREHOUSE CANDIDATE_SHIVUM_WH;
USE DATABASE CANDIDATE_SHIVUM;
USE SCHEMA BRONZE;

COPY INTO ECOM_SRC_CUSTOMERS
    FROM @ECOM_LANDING/customers/
    FILE_FORMAT = (FORMAT_NAME = 'ECOM_CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    INCLUDE_METADATA = (
        _SOURCE_FILE_NAME = METADATA$FILENAME,
        _SOURCE_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
        _LOADED_AT = METADATA$START_SCAN_TIME)
    ON_ERROR = ABORT_STATEMENT;

COPY INTO ECOM_SRC_PRODUCTS
    FROM @ECOM_LANDING/products/
    FILE_FORMAT = (FORMAT_NAME = 'ECOM_CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    INCLUDE_METADATA = (
        _SOURCE_FILE_NAME = METADATA$FILENAME,
        _SOURCE_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
        _LOADED_AT = METADATA$START_SCAN_TIME)
    ON_ERROR = ABORT_STATEMENT;

COPY INTO ECOM_SRC_ORDER_HEADERS
    FROM @ECOM_LANDING/order_headers/
    FILE_FORMAT = (FORMAT_NAME = 'ECOM_CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    INCLUDE_METADATA = (
        _SOURCE_FILE_NAME = METADATA$FILENAME,
        _SOURCE_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
        _LOADED_AT = METADATA$START_SCAN_TIME)
    ON_ERROR = ABORT_STATEMENT;

COPY INTO ECOM_SRC_ORDER_LINES
    FROM @ECOM_LANDING/order_lines/
    FILE_FORMAT = (FORMAT_NAME = 'ECOM_CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    INCLUDE_METADATA = (
        _SOURCE_FILE_NAME = METADATA$FILENAME,
        _SOURCE_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
        _LOADED_AT = METADATA$START_SCAN_TIME)
    ON_ERROR = ABORT_STATEMENT;

COPY INTO ECOM_SRC_INVENTORY
    FROM @ECOM_LANDING/inventory/
    FILE_FORMAT = (FORMAT_NAME = 'ECOM_CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    INCLUDE_METADATA = (
        _SOURCE_FILE_NAME = METADATA$FILENAME,
        _SOURCE_FILE_ROW_NUMBER = METADATA$FILE_ROW_NUMBER,
        _LOADED_AT = METADATA$START_SCAN_TIME)
    ON_ERROR = ABORT_STATEMENT;
